# Generated by Django 5.2.1 on 2025-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section1Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/section1/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
