# Generated by Django 5.2.1 on 2025-07-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_section1slideshow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Section2OurExpertise',
        ),
    ]
