# Generated by Django 5.2.1 on 2025-07-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_rename_service_section2ourexpertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section3Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='section3_backgrounds/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
